name: dorothy
"on":
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      DOROTHY: ${{ github.workspace }}
      NO_TTY: yes
      VERBOSE: yes
      CI_COMMIT_MESSAGE: "ci: adjustments"
      CI_COMMIT_NAME: "Continuous Integration"
      CI_COMMIT_EMAIL: "bot@bevry.me"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Configure"
        shell: bash
        run: |
          chmod +x "$DOROTHY/commands/"*
          source "$DOROTHY/sources/init.sh"
          dorothy dev
      - name: "Format"
        if: github.event_name == 'push'
        shell: bash
        run: |
          source "$DOROTHY/sources/init.sh"
          dorothy format || :
          if git diff --quiet &>/dev/null; then
            echo 'Already formatted.'
          else
            git config --global user.name "${{ env.CI_COMMIT_NAME }}"
            git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
            git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          fi
      - name: "Trunk Check"
        uses: trunk-io/trunk-action@v1
      - name: "Test"
        shell: bash
        run: |
          source "$DOROTHY/sources/init.sh"
          dorothy format
